replicaCount: 1

image:
  repository: your-docker-repo/your-flask-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

mongodb:
  host: your-mongodb-host
  port: 27017
  database: mydatabase
