name: Flask App Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask
      working-directory: .  # Adjust if your app code is in a subdirectory

    - name: Run Tests
      run: |
        python -m unittest discover -v
      working-directory: .  # Adjust if your tests are in a subdirectory

    - name: Build Docker Image
      run: |
        docker build -t my-flask-app .
      working-directory: .  # Adjust to the directory containing your Dockerfile

    - name: Check Docker Image
      run: |
        docker images
      working-directory: .  # Adjust to the directory containing your Dockerfile
