apiVersion: v1
kind: Service
metadata:
  name: my-project-service
spec:
  selector:
    app.kubernetes.io/name: my-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # Expose the service externally